# Generated by Django 2.1 on 2018-08-10 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('discipline_id_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('workload', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('subscription_date', models.DateTimeField(verbose_name='Subscription Date')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('subscription_date', models.DateField(verbose_name='subscription date')),
                ('area_of_domain', models.CharField(choices=[('CE', 'College of Engineering'), ('CAS', 'College of Arts and Sciences'), ('IA', 'International Affairs'), ('MCS', 'Mathematics and Computer Science'), ('MHS', 'Medicine and Health Sciences')], default='CE', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='students',
            field=models.ManyToManyField(to='uni.Student'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni.Teacher'),
        ),
    ]
